# Generated by Django 5.2 on 2025-06-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz', 'O‘zbekcha'), ('ru', 'Русский'), ('en', 'English')], default='ru', max_length=2),
        ),
    ]
