# Generated by Django 5.2 on 2025-07-14 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_organization_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='inn',
            field=models.CharField(default=123456789009, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='INN must be exactly 12 digits', regex='^\\d{12}$')]),
            preserve_default=False,
        ),
    ]
