# Generated by Django 5.2 on 2025-07-15 06:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organization_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Номер расчетного счёта (до 34 символов, IBAN поддерживается)', max_length=34, null=True, verbose_name='Расчётный счёт'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование банка'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Создатель организации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?\\d{7,20}$')], verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='organization',
            name='pnfl',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='PNFL must be exactly 14 digits', regex='^\\d{14}$')], verbose_name='ПНФЛ'),
        ),
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Краткое название'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='INN must be exactly 12 digits', regex='^\\d{12}$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Полное название'),
        ),
    ]
