# Generated by Django 5.2 on 2025-07-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_options_user_address_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
