# Generated by Django 5.2 on 2025-07-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_tasks',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество выполненных работ'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_tasks',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущее количество дел'),
        ),
    ]
