# Generated by Django 5.2 on 2025-06-09 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_input',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
