# Generated by Django 5.2 on 2025-07-31 12:06

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.project_file_upload_path, validators=[projects.models.validate_project_file_extension]),
        ),
    ]
