# Generated by Django 5.2.1 on 2025-06-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
