# Generated by Django 5.2 on 2025-07-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_status_organization_task_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
