# Generated by Django 5.2 on 2025-06-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_data_input'),
        ('tasks', '0003_task_data_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='projects.project'),
        ),
    ]
