# Generated by Django 5.2 on 2025-06-23 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_status_options_status_is_default_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='marked_to',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'employee'}, related_name='task_to_be_marked', to=settings.AUTH_USER_MODEL),
        ),
    ]
